import { type CSSProperties, useEffect, useRef, useState } from 'react'
import { Link, Route, Routes, useLocation } from 'react-router-dom'
import './App.css'
import Blog from './pages/Blog'
import Post from './pages/Post'
import Hobbies from './pages/Hobbies'
import Project from './pages/Project'
import Projects from './pages/Projects'
import WorkGraph from './components/WorkGraph'

// ─── Stars ─────────────────────────────────────────────────────────────────────

function Stars() {
  const canvasRef = useRef<HTMLCanvasElement>(null)

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    const ctx = canvas.getContext('2d')
    if (!ctx) return

    canvas.width = window.innerWidth
    canvas.height = window.innerHeight

    const count = Math.floor((canvas.width * canvas.height) / 6000)
    for (let i = 0; i < count; i++) {
      const x = Math.random() * canvas.width
      const y = Math.random() * canvas.height
      const r = Math.random() < 0.7 ? 0.4 : Math.random() < 0.5 ? 0.8 : 1.2
      const opacity = Math.random() * 0.55 + 0.1
      ctx.beginPath()
      ctx.arc(x, y, r, 0, Math.PI * 2)
      ctx.fillStyle = `rgba(228, 234, 248, ${opacity})`
      ctx.fill()
    }
  }, [])

  return <canvas ref={canvasRef} className="stars-canvas" />
}

// ─── Typing animation ──────────────────────────────────────────────────────────

const HERO_LINES = ['Built to', 'accelerate.']
const TOTAL_CHARS = HERO_LINES.reduce((sum, l) => sum + l.length, 0)
const LINE_OFFSETS = HERO_LINES.map((_, i) =>
  HERO_LINES.slice(0, i).reduce((sum, l) => sum + l.length, 0)
)

// ─── Data ──────────────────────────────────────────────────────────────────────

const workExperience = [
  {
    company: 'FTTP',
    role: 'Participant',
    period: 'April 2026',
    tag: 'incoming',
    details:
      'Incoming participant in Jane Street\'s spring insight program.',
  },
  {
    company: 'Jurni',
    role: 'Full-Stack App Developer',
    period: 'Jan 2026 - Present',
    tag: 'current',
    details:
      'Prototyping a React Native mobile app for a Birmingham-based ride-hailing startup, including rider-facing and driver-facing, and admin platforms.',
  },
  {
    company: 'Vela Partners',
    role: 'AI Research Intern',
    period: 'Dec 2025',
    details: 'Built a self-optimizing agentic pipeline within the MCP ecosystem using reinforcement learning and cross-client feedback. Improved predictive performance with 3x recall and over 2x precision-weighted F-score, and introduced new paradigms including Swarm Voting and the ACaSE workflow extending Stanford’s ACE framework.',
  },
  {
    company: 'Qoala',
    role: 'Software Engineer Intern',
    period: 'Jun - Aug 2025',
    details: 'Standardized a Golang dashboard across three insurance categories and fixed AWS Cloud data mappings for 100+ categories to improve reliability and consistency. Built a Vue.js OCR frontend for passport and ID verification, migrated AI tools to Gemini with prompt optimization, and developed a Python support chatbot using RAG and fine-tuning.',
  },
]

const otherExperience = [
  {
    company: 'UNDP',
    role: 'Consultant',
    period: 'Oct 2025 - Dec 2025',
    details: 'Developed a framework to evaluate positive externalities generated by small-to-medium enterprises.Outlined a quantitative modeling approach to demonstrate correlation between economic resilience and SME density',
  },
  {
    company: 'International Junior Honor Society',
    role: 'President & Committee Head',
    period: 'Jan 2022 - Jan 2025',
    details: 'Organized 3 international, holistic development winter camps for 180+ students from 14+ countries. Grew community membership by 2000 during term. Spearheaded service projects globally.',
  },
]

const awards = [
  {
    title: 'Math Olympiads - Gold',
    issuer: 'Various',
    year: '2016 - 2024',
    details: '3x AIME qualifier, with an average placement within the top 10 across global math olympiads over the course of 9 years.',
  },
  {
    title: 'National Olympiad in Informatics - Medalist',
    issuer: 'Indonesian Department of Education',
    year: '2022 - 2023',
    details: '2x NOI medalist in high school competitive programming. Placed 17th and 25th out of 28,000+ participants. Inducted into the national team.',
  },
  {
    title: 'IGCSE Top in the World for Additional Mathematics',
    issuer: 'Cambridge International Examinations',
    year: '2023 - 2025',
    details: 'Perfect score for the May/June series. Within the top 0.00003% of students worldwide.',
  },
]

const education = [
  {
    company: 'University of Oxford',
    role: 'Computer Science',
    period: '2025 - 2028',
    details: 'Integrated Masters degree. Scored 97 on the MAT. As a first year, I do not have grades yet, but I am on track to achieve a First Class on the basis of collections.',
  },
  {
    company: 'Jakarta Intercultural School',
    role: 'High School',
    period: '2023 - 2025',
    details: 'Graduated with 4.3/4.3 GPA, 1570 SAT score. Scored 5 on all AP coursework: Calculus AB, Language and Composition, Macroeconomics, Chemistry, Physics 1, Calculus BC, Literature and Composition, Microeconomics, Physics 2, Physics C: Mechanics, Physics C: Electricity & Magnetism',
  },
]

// ─── Hooks & Utilities ─────────────────────────────────────────────────────────

function useReveal(dep: string) {
  useEffect(() => {
    // Small timeout to ensure new DOM is painted after route change
    const t = setTimeout(() => {
      const els = document.querySelectorAll<HTMLElement>('[data-reveal]')
      const observer = new IntersectionObserver(
        (entries) => {
          entries.forEach(entry => {
            if (entry.isIntersecting) {
              entry.target.classList.add('revealed')
              observer.unobserve(entry.target)
            }
          })
        },
        { threshold: 0.08, rootMargin: '0px 0px -32px 0px' }
      )
      els.forEach(el => observer.observe(el))
      return () => observer.disconnect()
    }, 50)
    return () => clearTimeout(t)
  }, [dep])
}

// ─── Components ────────────────────────────────────────────────────────────────

function Nav() {
  const { pathname } = useLocation()
  const [collapsed, setCollapsed] = useState(false)
  const [isMobile, setIsMobile] = useState(false)
  const [drawerOpen, setDrawerOpen] = useState(false)

  useEffect(() => {
    const handleResize = () => {
      setIsMobile(window.innerWidth <= 900)
    }
    handleResize()
    window.addEventListener('resize', handleResize)
    return () => window.removeEventListener('resize', handleResize)
  }, [])

  useEffect(() => {
    if (!isMobile) {
      document.body.classList.toggle('nav-collapsed', collapsed)
      setDrawerOpen(false)
    } else {
      document.body.classList.remove('nav-collapsed')
    }
  }, [collapsed, isMobile])

  if (isMobile) {
    const closeDrawer = () => setDrawerOpen(false)

    return (
      <>
        <nav className="nav-mobile">
          <button
            className="nav-logo-toggle"
            onClick={() => setDrawerOpen(true)}
            aria-label="Open navigation"
            aria-expanded={drawerOpen}
          >
            <span className="nav-logo-text">NS<span className="c-violet">.</span></span>
          </button>
          <button
            className="nav-burger"
            onClick={() => setDrawerOpen(o => !o)}
            aria-label={drawerOpen ? 'Close navigation' : 'Open navigation'}
            aria-expanded={drawerOpen}
          >
            <span />
          </button>
        </nav>

        <button
          className={`nav-drawer-overlay${drawerOpen ? ' is-open' : ''}`}
          aria-label="Close navigation"
          onClick={closeDrawer}
        />

        <aside className={`nav-drawer${drawerOpen ? ' is-open' : ''}`} aria-hidden={!drawerOpen}>
          <div className="nav-drawer-header">
            <span className="nav-logo-text">NS<span className="c-violet">.</span></span>
            <button
              className="nav-drawer-close"
              onClick={closeDrawer}
              aria-label="Close navigation"
            >
              ×
            </button>
          </div>
          <div className="nav-drawer-links">
            {pathname === '/' ? (
              <>
                <a href="#work" className="nav-link" onClick={closeDrawer}>Work</a>
                <a href="#about" className="nav-link" onClick={closeDrawer}>About</a>
                <a href="#contact" className="nav-link" onClick={closeDrawer}>Contact</a>
              </>
            ) : (
              <Link to="/" className="nav-link" onClick={closeDrawer}>Home</Link>
            )}
            <Link
              to="/projects"
              className={`nav-link${pathname === '/projects' ? ' nav-active' : ''}`}
              onClick={closeDrawer}
            >
              Projects
            </Link>
            <Link
              to="/blog"
              className={`nav-link${pathname.startsWith('/blog') ? ' nav-active' : ''}`}
              onClick={closeDrawer}
            >
              Writing
            </Link>
            <Link
              to="/me"
              className={`nav-link${pathname === '/me' ? ' nav-active' : ''}`}
              onClick={closeDrawer}
            >
              This is Me
            </Link>
          </div>
        </aside>
      </>
    )
  }

  return (
    <>
      <nav className={`nav-desktop${collapsed ? ' nav-collapsed' : ''}`}>
        <button
          className="nav-logo-toggle"
          onClick={() => setCollapsed(c => !c)}
          aria-label={collapsed ? 'Open sidebar' : 'Close sidebar'}
        >
          <span className="nav-logo-text">NS<span className="c-violet">.</span></span>
          <span className="nav-logo-arrow">‹</span>
        </button>
        <div className="nav-links">
          {pathname === '/' ? (
            <>
              <a href="#work" className="nav-link">Work</a>
              <a href="#about" className="nav-link">About</a>
              <a href="#contact" className="nav-link">Contact</a>
            </>
          ) : (
            <Link to="/" className="nav-link">Home</Link>
          )}
          <Link
            to="/projects"
            className={`nav-link${pathname === '/projects' ? ' nav-active' : ''}`}
          >
            Projects
          </Link>
          <Link
            to="/blog"
            className={`nav-link${pathname.startsWith('/blog') ? ' nav-active' : ''}`}
          >
            Writing
          </Link>
          <Link
            to="/me"
            className={`nav-link${pathname === '/me' ? ' nav-active' : ''}`}
          >
            This is Me
          </Link>
        </div>
      </nav>

      {/* Ghost toggle when nav is hidden */}
      {collapsed && (
        <button
          className="nav-ghost-toggle"
          onClick={() => setCollapsed(false)}
          aria-label="Open sidebar"
        />
      )}
    </>
  )
}

function Hero() {
  const [count, setCount] = useState(0)
  const [phase, setPhase] = useState<'typing' | 'untyping'>('typing')

  useEffect(() => {
    let t: ReturnType<typeof setTimeout>
    if (phase === 'typing') {
      if (count < TOTAL_CHARS) {
        t = setTimeout(() => setCount(c => c + 1), 65)
      } else {
        t = setTimeout(() => setPhase('untyping'), 1800)
      }
    } else {
      if (count > 0) {
        t = setTimeout(() => setCount(c => c - 1), 35)
      } else {
        t = setTimeout(() => setPhase('typing'), 500)
      }
    }
    return () => clearTimeout(t)
  }, [count, phase])

  return (
    <section className="hero" id="home">
      <div className="hero-top">
        <div className="hero-header">
          <span>Nobel Suhendra</span>
          <span className="c-teal">1st year Oxford CS</span>
        </div>
        <div className="hero-rule" />
      </div>

      <h1 className="hero-headline">
        {HERO_LINES.map((line, li) => {
          const lineStart = LINE_OFFSETS[li]
          const cursorPos = count - lineStart
          const cursorHere = cursorPos >= 0 && cursorPos <= line.length

          const chars = line.split('').map((char, ci) => (
            <span key={ci} className={`hero-char${lineStart + ci < count ? ' char-typed' : ''}`}>
              {char}
            </span>
          ))

          if (cursorHere) chars.splice(cursorPos, 0, <span key="cur" className="hero-cursor" />)

          return (
            <span key={li} className={`hero-line-wrap${li === HERO_LINES.length - 1 ? ' hero-line-accent' : ''}`}>
              {chars}
              {li < HERO_LINES.length - 1 && <br />}
            </span>
          )
        })}
      </h1>

      <div className="hero-bottom">
        <div className="hero-rule" />
        <div className="hero-footer">
          <span>Full-stack developer · <span className="c-blue">Jakarta, Indonesia</span></span>
          <a href="#work" className="hero-cta u-line">View work →</a>
        </div>
      </div>
    </section>
  )
}



// const FOCUSES = ['Full-stack', 'Mobile apps', 'Agentic AI', 'Competitive programming', 'Quantum computing']

function About() {
  return (
    <section className="about-section" id="about">
      <div className="section-label" data-reveal>About</div>

      {/* Full-width intro copy above the grid */}
      <div className="about-content">
        <p data-reveal style={{ '--i': 0 } as CSSProperties}>
          Hey! I'm Nobel, a CS undergrad at  <span className="c-violet">Oxford</span>, full-stack SWE and part-time app developer.
          I got super into competitive programming in high school and became a <span className="c-violet">2x NOI medalist</span>.
          Ever since, I've been mostly self-taught in programming and all things building.
          I'm currently tinkering with a couple side projects and exploring  <span className="c-violet">AI &amp; quantum computing research</span>.
        </p>
      </div>

      {/* Photo + experience side-by-side */}
      <div className="about-grid">
        <div className="about-photo" data-reveal style={{ '--i': 1 } as CSSProperties}>
          <img
            src="/src/assets/profile.jpg"
            alt="Placeholder portrait"
            className="about-photo-img"
          />
        </div>

        <div className="about-content">
          <div className="exp-subsection" data-reveal style={{ '--i': 2 } as CSSProperties}>
            <div className="exp-subsection-label">Experience</div>
            <div className="experience-list">
              {workExperience.map((e) => (
                <div key={e.company} className="exp-row exp-row-hoverable">
                  <div>
                    <div className="exp-company-row">
                      <span className="exp-company">{e.company}</span>
                      {e.tag && (
                        <span className={`exp-tag exp-tag-${e.tag}`}>
                          {e.tag === 'incoming'
                            ? 'Incoming'
                            : e.tag === 'current'
                              ? 'Current'
                              : e.tag}
                        </span>
                      )}
                    </div>
                    <span className="exp-role">{e.role}</span>
                    <span className="exp-details">{e.details}</span>
                  </div>
                  <span className="exp-period">{e.period}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="exp-subsection" data-reveal style={{ '--i': 3 } as CSSProperties}>
            <div className="exp-subsection-label">Education</div>
            <div className="experience-list">
              {education.map((e) => (
                <div key={e.company} className="exp-row exp-row-hoverable">
                  <div>
                    <span className="exp-company">{e.company}</span>
                    <span className="exp-role">{e.role}</span>
                    <span className="exp-details">{e.details}</span>
                  </div>
                  <span className="exp-period">{e.period}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Infinite scrolling ticker */}
      {/* <div className="about-ticker" aria-hidden>
        <div className="about-ticker-track">
          {[...FOCUSES, ...FOCUSES, ...FOCUSES].map((f, i) => (
            <span key={i} className="about-ticker-item">{f}</span>
          ))}
        </div>
      </div> */}
    </section>
  )
}

function Others() {
  return (
    <section className="others-section">
      <div className="section-label" data-reveal>Others</div>

      <div className="about-content">
        <p data-reveal style={{ '--i': 0 } as CSSProperties}>
          Leadership, accomplishments, and the things I&apos;m proud of outside pure software engineering.
        </p>
      </div>

      <div className="about-content">
        <div className="exp-subsection" data-reveal style={{ '--i': 1 } as CSSProperties}>
          <div className="exp-subsection-label">Leadership</div>
          <div className="experience-list">
            {otherExperience.map((e) => (
              <div key={e.company} className="exp-row exp-row-hoverable">
                <div>
                  <span className="exp-company">{e.company}</span>
                  <span className="exp-role">{e.role}</span>
                  <span className="exp-details">{e.details}</span>
                </div>
                <span className="exp-period">{e.period}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="exp-subsection" data-reveal style={{ '--i': 2 } as CSSProperties}>
          <div className="exp-subsection-label">Awards</div>
          <div className="experience-list">
            {awards.map((a) => (
              <div key={a.title} className="exp-row exp-row-hoverable">
                <div>
                  <span className="exp-company">{a.title}</span>
                  <span className="exp-role">
                    {a.issuer} · {a.year}
                  </span>
                  <span className="exp-details">{a.details}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}

function Contact() {
  return (
    <section className="contact-section" id="contact">
      <h2 className="contact-heading" data-reveal>Let's <span className="c-violet">build.</span></h2>
      <a href="mailto:nobel@suhendra.com" className="contact-email" data-reveal style={{ '--i': 1 } as CSSProperties}>
        nobel@suhendra.com
      </a>
      <a href="tel:+447412967062" className="contact-phone" data-reveal style={{ '--i': 3 } as CSSProperties}>
        +44 7412 967 062
      </a>
    </section>
  )
}

function Footer() {
  return (
    <footer>
      <span>© 2026 Nobel Suhendra</span>
      <div className="footer-links">
        <a href="https://github.com/nobelsu" target="_blank" rel="noopener noreferrer">GitHub</a>
        <a href="https://linkedin.com/in/nobelsu" target="_blank" rel="noopener noreferrer">LinkedIn</a>
        <a href="#contact">Contact</a>
      </div>
    </footer>
  )
}

function Home() {
  return (
    <>
      <main>
        <Hero />
        <About />
        <WorkGraph />
        <Others />
        <Contact />
      </main>
      <Footer />
    </>
  )
}

// ─── App ───────────────────────────────────────────────────────────────────────

export default function App() {
  const { pathname } = useLocation()
  useReveal(pathname)

  return (
    <>
      <Stars />
      <Nav />
      <div className="route-wrapper" key={pathname}>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/blog" element={<Blog />} />
          <Route path="/blog/:slug" element={<Post />} />
          <Route path="/me" element={<Hobbies />} />
          <Route path="/projects" element={<Projects />} />
          <Route path="/projects/:slug" element={<Project />} />
        </Routes>
      </div>
    </>
  )
}
