export interface ExperienceEntry {
  company: string
  role: string
  period: string
  tag?: string
  details: string
}

export const workExperience: ExperienceEntry[] = [
  {
    company: 'Light',
    role: 'AI Engineer Intern',
    period: 'Jul 2026 - Present',
    tag: 'current',
    details:
      'AI-native FinOps start-up. Building "organic" software for the live enterprise.',
  },
  {
    company: 'Jane Street',
    role: 'FTTP Participant',
    period: 'Apr 2026',
    details: "Participant in Jane Street's FTTP spring insight program.",
  },
  {
    company: 'Vela Partners',
    role: 'AI Research Intern',
    period: 'Dec 2025',
    details:
      'Quant VC start-up. Built a self-optimizing agentic pipeline within the MCP ecosystem using a reinforcement learning training loop and cross-client feedback. Achieved 3x recall and over 2x precision-weighted F-score through MCP server augmentation, and designed new agentic paradigms including Swarm Voting and an extension of Agentic Context Engineering.',
  },
  {
    company: 'Qoala',
    role: 'Software Engineer Intern',
    period: 'Jun - Aug 2025',
    details:
      'InsurTech start-up. Standardized a Golang dashboard across 3 of 5 insurance categories and fixed AWS Cloud data mappings for ~100 categories. Built a Vue.js OCR frontend for identity-document uploads, migrated AI tooling to Gemini, and developed a Python RAG + QLoRA fine-tuned chatbot streamlining ~70% of client support requests.',
  },
]

export const education: ExperienceEntry[] = [
  {
    company: 'University of Oxford',
    role: 'Computer Science (MCompSci) · St. Anne’s College',
    period: '2025 - 2028',
    details:
      'Integrated Masters degree. Scored 97 on the MAT. On track for a First Class.',
  },
  {
    company: 'Jakarta Intercultural School',
    role: 'High School',
    period: 'Jul 2023 - May 2025',
    details:
      'GPA 4.3/4.3, SAT 1570, 3x AIME qualifier, 5 on all APs. Mu Alpha Theta (President), Code Club (Officer), VEX Robotics (Team Captain), Badminton Service Club.',
  },
]

export const otherExperience: ExperienceEntry[] = [
  {
    company: 'UNDP',
    role: 'Consultant',
    period: 'Oct 2025 - Dec 2025',
    details:
      'Developed a framework to evaluate positive externalities generated by small-to-medium enterprises. Outlined a quantitative modeling approach to demonstrate correlation between economic resilience and SME density',
  },
  {
    company: 'International Junior Honor Society',
    role: 'President & Committee Head',
    period: 'Jan 2022 - Jan 2025',
    details:
      'Organized 3 international, holistic development winter camps for 180+ students from 14+ countries. Grew community membership by 2000 during term. Spearheaded service projects globally.',
  },
]

export const awards = [
  {
    title: 'Math Olympiads - Gold',
    issuer: 'Various',
    year: '2016 - 2024',
    details:
      '3x AIME qualifier, with an average placement within the top 10 across global math olympiads over the course of 9 years.',
  },
  {
    title: 'National Olympiad in Informatics - Medalist',
    issuer: 'Indonesian Department of Education',
    year: '2022 - 2023',
    details:
      '2x NOI medalist in high school competitive programming. Placed 17th and 25th out of 28,000+ participants. Inducted into the national team.',
  },
  {
    title: 'IGCSE Top in the World for Additional Mathematics',
    issuer: 'Cambridge International Examinations',
    year: '2023',
    details: 'Perfect score for the May/June series. Within the top 0.00003% of students worldwide.',
  },
]

export const currents = [
  { key: 'reading', val: 'Butter by Asako Yuzuki' },
  { key: 'building', val: 'Ruby, a "game-ified" screen-time solution' },
  { key: 'thinking', val: 'Probs about some stupid AI "what ifs"' },
  { key: 'playing', val: 'Badminton! My toes hurt.' },
]

export const playlists = [
  { name: 'k/j', url: 'https://open.spotify.com/playlist/6UfkzSd6XxN1tGawUX64Nw', mood: '202 tracks' },
]

export const interests = [
  { name: 'Japanese literature', note: 'Murakami numba one', image: '/assets/japanese.jpg' },
  { name: 'Competitive programming', note: 'Gonna be on the CF grind this summer', image: '/assets/cp.jpg' },
  { name: 'Sudoku', note: 'LOWKEY meditative', image: '/assets/sudoku.jpg' },
  { name: 'Baking', note: "Specifically baguettes. (I promise I'm learning!!)", image: '/assets/baking.jpg' },
  { name: 'Fencing', note: 'Might overtake badminton as my fav sport', image: '/assets/fencing.jpg' },
  { name: 'Side-quests??', note: "One day I'll finish the storybook. One day...", image: '/assets/quest.jpg' },
]
